# Homework 02: Iris Classification

Homework 02 entails us improving the Iris classification models:

**Ways to improve on the Iris models**

1. Adjust hyperparameters of models
2. Add features
     - Try Length / Width
     - Use Unsupervised model (K-Means)
3. Add models to set
    - XGBoost
    - lightGBM
4. Add Visualization

In [1]:
# import libraries

import pandas as pd
from pandas.plotting import scatter_matrix
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
import xgboost as xgb

In [2]:
# ignore warnings

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

## Load dataset

In [3]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pd.read_csv(url, names=names)

## Explore Data

In [4]:
# shape
print("Shape: ", dataset.shape, '\n')

# head
print("First records of data:\n", dataset.head(), '\n')

# class distribution
print('Class Distribution:')
print(dataset.groupby('class').size())

Shape:  (150, 5) 

First records of data:
    sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa 

Class Distribution:
class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64


In [5]:
print("Statistical description of data:\n",dataset.describe())

Statistical description of data:
        sepal-length  sepal-width  petal-length  petal-width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


---

## Split out validation dataset

In [6]:
array = dataset.values
X = array[:,0:4]
Y = array[:,4]
validation_size = 0.20
seed = 7

X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(
    X,
    Y,
    test_size=validation_size,
    random_state=seed
)

## Create Model Shells

In [19]:
models = []
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('RF', RandomForestClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))

models

[('LR',
  LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
            intercept_scaling=1, max_iter=100, multi_class='warn',
            n_jobs=None, penalty='l2', random_state=None, solver='warn',
            tol=0.0001, verbose=0, warm_start=False)),
 ('LDA',
  LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                solver='svd', store_covariance=False, tol=0.0001)),
 ('KNN',
  KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
             metric_params=None, n_jobs=None, n_neighbors=5, p=2,
             weights='uniform')),
 ('CART',
  DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, presort=False, random_state=None,
              splitter='best')),
 ('RF'

## Spot test each model with Cross-Validation

In [8]:
# Test options and evaluation metric
seed = 7
scoring = 'accuracy'

results = []
names = []

# evaluate each model in turn
for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state=seed)
    cv_results = model_selection.cross_val_score(
        model, X_train, Y_train, cv=kfold, scoring=scoring
    )
    results.append(cv_results)
    names.append(name)
    msg = f"{name}: {cv_results.mean():0.4f} ({cv_results.std():0.4f})"
    print(msg)

LR: 0.9667 (0.0408)
LDA: 0.9750 (0.0382)
KNN: 0.9833 (0.0333)
CART: 0.9667 (0.0408)
RF: 0.9750 (0.0382)
NB: 0.9750 (0.0534)
SVM: 0.9917 (0.0250)


## Make predictions on validation dataset

K-Nearest Neighbors:

In [9]:
def make_prediction(model):
    print(model)
    model.fit(X_train, Y_train)
    predictions = model.predict(X_validation)

    print("Accuracy Score:", accuracy_score(Y_validation, predictions))
    print("\nConfusion Matrix:\n", confusion_matrix(Y_validation, predictions))
    print("\nClassification Report:\n", classification_report(Y_validation, predictions))

In [10]:
make_prediction(KNeighborsClassifier())

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')
Accuracy Score: 0.9

Confusion Matrix:
 [[ 7  0  0]
 [ 0 11  1]
 [ 0  2  9]]

Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.85      0.92      0.88        12
 Iris-virginica       0.90      0.82      0.86        11

      micro avg       0.90      0.90      0.90        30
      macro avg       0.92      0.91      0.91        30
   weighted avg       0.90      0.90      0.90        30



In [11]:
for name, model in models:
    print(name)
    make_prediction(model)
    print('\n\n')

LR
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)
Accuracy Score: 0.8

Confusion Matrix:
 [[ 7  0  0]
 [ 0  7  5]
 [ 0  1 10]]

Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.88      0.58      0.70        12
 Iris-virginica       0.67      0.91      0.77        11

      micro avg       0.80      0.80      0.80        30
      macro avg       0.85      0.83      0.82        30
   weighted avg       0.83      0.80      0.80        30




LDA
LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)
Accuracy Score: 0.9666666666666667

Confusion Matrix:
 [[ 7  0  0]
 [ 0 11  1]
 [ 0

---

## Use XGBoost

In [14]:
dataset['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [18]:
# map the iris class to numerical values
class_map = {
    'Iris-setosa': 0,
    'Iris-versicolor': 1,
    'Iris-virginica': 2
}
Y_new = [class_map[iris_class] for iris_class in Y]

# split data into train and validation sets
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(
    X,
    Y_new,
    test_size=validation_size,
    random_state=seed
)

d_train = xgb.DMatrix(X_train, label=Y_train)
d_validate = xgb.DMatrix(X_validation, label=Y_validation)

# set xgboost params
param = {
    'max_depth': 3,
    'eta': 0.3,
    'silent': 1,
    'objective': 'multi:softprob',
    'num_class': 3
}
num_round = 20

# train model
bst = xgb.train(param, d_train, num_round)

# predict
predictions = bst.predict(d_validate)

# pick best prediction results
best_predictions = np.asarray([np.argmax(line) for line in predictions])

print(accuracy_score(Y_validation, best_predictions))

0.9
